## 第２項　NumPy配列の生成

In [ ]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])

In [5]:
a

array([1, 2, 3, 4])

In [10]:
aa =np.array([[1,2],[3,4]])

In [11]:
aa

array([[1, 2],
       [3, 4]])

In [12]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [13]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(0,1,0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

### NumPy配列形状確認

In [20]:
a.ndim

1

In [21]:
a.shape

(4,)

In [22]:
aa.ndim

2

In [23]:
aa.shape

(2, 2)

ndimは、次元数が確認できる。  shepeは、各次元の要素数を確認できる。

### 配列の形状変更

In [24]:
aa.reshape(4)

array([1, 2, 3, 4])

In [25]:
a.reshape((2,2))

array([[1, 2],
       [3, 4]])

reshapeで１次配列に変換したり、２次元形状に戻すなどができる。

## 第３項　NumPy配列の取り出し

### NumPy配列の取り出し

In [30]:
import numpy as np
b = np.arange(10)
b[2]

2

In [31]:
b[2:5]

array([2, 3, 4])

NumPy配列の要素は、スライスを利用して取り出すことができる

### 部分行列の取り出し

In [32]:
bb = np.arange(16).reshape((4,4))

In [33]:
bb

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
bb [1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

配列は、0から数え終わりの数字を入れないのでこの場合、２列目から3列目、２行目から３行目の選択範囲を抜き出す

## 第４項 NumPy配列同士の演算

In [36]:
import numpy as np

In [37]:
c = np.array([1,2,3])
d = np.array([3,2,5])
c + d

array([4, 4, 8])

それぞれcとdが加算され、結果が表示される

In [38]:
np.array([1,2,3])+np.array([3,4,5])


array([4, 6, 8])

In [40]:
cc = np.array([[1,2],[3,4]])
dd = np.array([[5,1],[2,3]])
cc + dd

array([[6, 3],
       [5, 7]])

### 行列積

In [41]:
cc.dot(dd)

array([[ 9,  7],
       [23, 15]])

行列の積を計算するにはdotメソッドを利用する。<br>
＊　とは、違うので注意

## 第５項 NumPy配列とスカラー値の演算

In [46]:
import numpy as np
f = np.array([1,3,7])

In [48]:
f + 4

array([ 5,  7, 11])

In [49]:
3 * f

array([ 3,  9, 21])

### ブロードキャストの一般処理

In [52]:
gg = np.arange(9).reshape((3,3))

In [54]:
h = np.array([2,3,5])

In [55]:
gg

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
gg + h

array([[ 2,  4,  7],
       [ 5,  7, 10],
       [ 8, 10, 13]])

行列の各行に同様の値を加算することができる

## 第６項　演習問題

（１）

In [ ]:
import numpy as np

In [61]:
j = np.array([[3,2],[4,5]])

In [62]:
j

array([[3, 2],
       [4, 5]])

（２）

In [68]:
k = np.array([3,5])

In [69]:
k

array([3, 5])

（３）　行列積を計算

In [71]:
j*k

array([[ 9, 10],
       [12, 25]])

（４）　

In [72]:
ll = np.arange(25).reshape((5,5))

In [73]:
ll

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [83]:
ll[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

部分行列を取り出す時は[]内に1次元目と２次元目の取り出し範囲をカンマで区切って指定する